# Generated by Django 5.2.17 on 2026-09-11 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_exportjob_monthlydigest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.expense')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='expenses.expenseitem')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_shares', to='expenses.participant')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='shared_expenses', to='expenses.participant'),
        ),
        migrations.AddConstraint(
            model_name='expenseitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='item_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_participant_per_user'),
        ),
        migrations.AddConstraint(
            model_name='itemshare',
            constraint=models.UniqueConstraint(fields=('item', 'participant'), name='uniq_share_per_item_participant'),
        ),
        migrations.AddConstraint(
            model_name='itemshare',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='share_weight_positive'),
        ),
    ]
