# Generated by Django 5.2.17 on 2026-09-11 06:43

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expenseitem_participant_itemshare_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='uniq_category_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='participant',
            name='uniq_participant_per_user',
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'category', 'spent_on'], name='expense_user_cat_date'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='uniq_category_name_per_user_ci'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), name='uniq_participant_name_per_user_ci'),
        ),
    ]
