# Generated by Django 5.2.17 on 2026-09-11 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expense_note_fts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settled_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='expenses.participant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-settled_at', '-id'],
                'indexes': [models.Index(fields=['user', 'participant'], name='expenses_se_user_id_0ab1cb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='settlement_amount_positive')],
            },
        ),
    ]
