# Generated by Django 5.2.17 on 2026-09-14 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenses', to='expenses.participant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='is_self',
            field=models.BooleanField(default=False),
        ),
    ]
