# Generated by Django 5.2.17 on 2026-09-14 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_rename_self_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='settlement',
            name='settlement_amount_positive',
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='settlement_amount_not_zero'),
        ),
    ]
