# Generated by Django 5.2.17 on 2026-09-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Used to sign in to support and to reset your password.', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
