# Generated by Django 5.2.17 on 2026-09-28 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_backfill_email_verified_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("login_succeeded", "Login succeeded"),
                            ("login_failed", "Login failed"),
                            ("login_blocked", "Login blocked (rate limited)"),
                            ("logged_out", "Logged out"),
                            ("signed_up", "Signed up"),
                            ("email_verified", "Email verified"),
                            ("password_changed", "Password changed"),
                            ("password_reset_requested", "Password reset requested"),
                            ("password_reset_completed", "Password reset completed"),
                            ("tokens_revoked", "Tokens revoked"),
                            ("account_deleted", "Account deleted"),
                        ],
                        max_length=32,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=150)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, max_length=64)),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "created_at"],
                        name="accounts_se_event_527d15_idx",
                    )
                ],
            },
        ),
    ]
