# Generated by Django 5.2.17 on 2026-09-28 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_securityevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("login_succeeded", "Login succeeded"),
                    ("login_failed", "Login failed"),
                    ("login_blocked", "Login blocked (rate limited)"),
                    ("logged_out", "Logged out"),
                    ("signed_up", "Signed up"),
                    ("email_verified", "Email verified"),
                    ("password_changed", "Password changed"),
                    ("password_reset_requested", "Password reset requested"),
                    ("password_reset_completed", "Password reset completed"),
                    ("tokens_revoked", "Tokens revoked"),
                    ("account_deleted", "Account deleted"),
                    ("mfa_challenge_passed", "Two-step code accepted"),
                    ("mfa_challenge_failed", "Two-step code rejected"),
                    ("mfa_enabled", "Two-step sign-in turned on"),
                    ("mfa_disabled", "Two-step sign-in turned off"),
                    ("recovery_code_used", "Recovery code used"),
                    ("recovery_codes_regenerated", "Recovery codes regenerated"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret", models.CharField(max_length=32)),
                ("confirmed", models.BooleanField(default=False)),
                ("last_used_step", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="totp_device",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecoveryCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_hash", models.CharField(max_length=128)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "used_at"],
                        name="accounts_re_user_id_51e9a4_idx",
                    )
                ],
            },
        ),
    ]
