# Generated by Django 5.2.17 on 2026-09-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_securityevent_event_totpdevice_recoverycode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("login_succeeded", "Login succeeded"),
                    ("login_failed", "Login failed"),
                    ("login_blocked", "Login blocked (rate limited)"),
                    ("logged_out", "Logged out"),
                    ("signed_up", "Signed up"),
                    ("email_verified", "Email verified"),
                    ("password_changed", "Password changed"),
                    ("password_reset_requested", "Password reset requested"),
                    ("password_reset_completed", "Password reset completed"),
                    ("tokens_revoked", "Tokens revoked"),
                    ("account_deleted", "Account deleted"),
                    ("mfa_challenge_passed", "Two-step code accepted"),
                    ("mfa_challenge_failed", "Two-step code rejected"),
                    ("mfa_enabled", "Two-step sign-in turned on"),
                    ("mfa_disabled", "Two-step sign-in turned off"),
                    ("recovery_code_used", "Recovery code used"),
                    ("recovery_codes_regenerated", "Recovery codes regenerated"),
                    ("google_login_succeeded", "Google sign-in succeeded"),
                    ("google_login_failed", "Google sign-in failed"),
                ],
                max_length=32,
            ),
        ),
    ]
