# Generated by Django 5.2.17 on 2026-09-29 19:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_securityevent_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="securityevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("login_succeeded", "Login succeeded"),
                    ("login_failed", "Login failed"),
                    ("login_blocked", "Login blocked (rate limited)"),
                    ("logged_out", "Logged out"),
                    ("signed_up", "Signed up"),
                    ("email_verified", "Email verified"),
                    ("password_changed", "Password changed"),
                    ("password_reset_requested", "Password reset requested"),
                    ("password_reset_completed", "Password reset completed"),
                    ("tokens_revoked", "Tokens revoked"),
                    ("account_deleted", "Account deleted"),
                    ("mfa_challenge_passed", "Two-step code accepted"),
                    ("mfa_challenge_failed", "Two-step code rejected"),
                    ("mfa_enabled", "Two-step sign-in turned on"),
                    ("mfa_disabled", "Two-step sign-in turned off"),
                    ("recovery_code_used", "Recovery code used"),
                    ("recovery_codes_regenerated", "Recovery codes regenerated"),
                    ("google_login_succeeded", "Google sign-in succeeded"),
                    ("google_login_failed", "Google sign-in failed"),
                    ("device_signed_out", "Device signed out"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="SignedInDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("web", "Web"), ("api", "API")], max_length=3
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                (
                    "refresh_jti",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("label", models.CharField(blank=True, max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signed_in_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_seen_at", "id"],
            },
        ),
    ]
