"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment. Declaring types and defaults here means a missing or
# malformed value fails loudly at startup rather than silently becoming
# a string like "False" (which is truthy).
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
)

# Read .env if present. It is gitignored; .env.example documents the keys.
environ.Env.read_env(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
# No default on purpose: an unset SECRET_KEY should crash, not fall back
# to a shared value that silently ships to production.
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False so that forgetting to set it fails safe.
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")

# How many reverse proxies (nginx, a load balancer) stand in front of the
# app. Each one appends the address it received the request from to
# X-Forwarded-For, so the trustworthy client address is that many entries
# from the *right*; anything further left was written by the client and can
# be anything. 0 means no proxy: REMOTE_ADDR is the client. Every rate limit
# (DRF's throttles and accounts/ratelimit.py) reads the address this way.
# Defaults to 1 when USE_X_FORWARDED_PROTO says a proxy terminates TLS.
# Where the admin site lives, with a trailing slash. See config/urls.py.
ADMIN_URL = env("ADMIN_URL", default="admin/").strip("/") + "/"

TRUSTED_PROXY_COUNT = env.int(
    "TRUSTED_PROXY_COUNT", default=1 if env.bool("USE_X_FORWARDED_PROTO", default=False) else 0
)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "rest_framework",
    "expenses",
    # Phase 20, an API for a remote frontend (DECISIONS D41-D43).
    "corsheaders",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
]

# Custom user model. Must be set before the first migration is applied;
# swapping it afterwards is a painful data migration.
AUTH_USER_MODEL = "accounts.User"

# Where LoginRequiredMixin sends anonymous users, and where login/logout
# land afterwards. Accepts a URL name, so the path can change without
# touching settings.
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "expenses:dashboard"
LOGOUT_REDIRECT_URL = "expenses:dashboard"

# Email. The console backend prints messages to stdout instead of sending
# them, which is what makes the password reset flow testable in development
# without an SMTP server. Production overrides EMAIL_BACKEND via the
# environment; nothing in the code needs to change.
EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="no-reply@expense-tracker.local")
# SMTP, for EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend on a
# hosted server. Defaults are Django's own, so nothing changes until set.
EMAIL_HOST = env("EMAIL_HOST", default="localhost")
EMAIL_PORT = env.int("EMAIL_PORT", default=25)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)

# How long a password reset link stays valid. Django's default is 3 days,
# which is generous for a credential-bearing URL that may sit in an inbox.
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24  # 24 hours

# Swaps in a fast password hasher for the test run only. See the module
# docstring: 20.5s -> 0.5s on the current suite.
TEST_RUNNER = "config.test_runner.FastTestRunner"


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Directly after SecurityMiddleware and before everything else, so a
    # static file is served without paying for session lookup, auth or CSRF.
    # Ordering is not cosmetic here: placed last it would still work and
    # would do all that work first.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # Before anything that can answer a request itself (CommonMiddleware's
    # redirects), so those answers carry CORS headers too. After WhiteNoise,
    # because static files are never fetched cross-origin by the frontend.
    "corsheaders.middleware.CorsMiddleware",
    # Before everything that can log, so the id is set by the time any
    # other middleware, view or exception handler emits a line. After
    # WhiteNoise, because a static file is not worth an id.
    "config.middleware.RequestIDMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Project-wide templates (base.html, later registration/). App
        # templates still resolve via APP_DIRS; this directory is searched
        # first, which is also how you override a third-party app's template.
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Nav badges, previously passed by hand from the handful of
                # views that happened to remember. A context processor runs
                # for every template render, which is the point and also the
                # cost -- see the docstring.
                "expenses.context_processors.nav_summary",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Parsed from a DATABASE_URL, so moving to Postgres later is a config
# change rather than a code change.
DATABASES = {
    "default": env.db_url(
        "DATABASE_URL",
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Where collectstatic gathers files for a production server to serve.
# Unset, collectstatic refuses to run, which is the usual first failure of a
# container build.
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise lets the application server serve its own static files, so
# there is no nginx to configure and no bucket to sync. It compresses and
# fingerprints at collectstatic time, so files are cached forever and a
# changed file gets a new name.
#
# The honest limit: this is fine up to real traffic, and at real traffic a
# CDN in front is the answer. It is not a worse choice than nginx, it is a
# simpler one that stops being enough later.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Celery
# https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html

# Separate Redis databases: a flushed result backend must not take the
# pending task queue with it.
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://localhost:6379/1")

# JSON only. Celery's old pickle serializer executes arbitrary code on
# deserialisation, so anyone who can write to the broker gets remote code
# execution on every worker.
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

CELERY_TIMEZONE = TIME_ZONE

# Acknowledge a task only after it finishes, not when it is received. If a
# worker is killed mid-task the broker redelivers it instead of losing it.
# The cost is that tasks must be idempotent, because redelivery means a task
# can run twice.
CELERY_TASK_ACKS_LATE = True

# With acks_late, a worker that has prefetched ten tasks and dies redelivers
# all ten. Fetching one at a time keeps that blast radius small; it matters
# for slow I/O-bound tasks and costs throughput only for very fast ones.
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# A hung task holds a worker process forever without these. The soft limit
# raises an exception the task can catch and clean up after; the hard limit
# kills the process.
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 5
CELERY_TASK_TIME_LIMIT = 60 * 10

# Run tasks inline instead of dispatching them. Set by the test settings so
# the suite needs no broker; never enable it in production, where it would
# silently make every "background" job block the request.
CELERY_TASK_ALWAYS_EAGER = env.bool("CELERY_TASK_ALWAYS_EAGER", default=False)
CELERY_TASK_EAGER_PROPAGATES = True


# Bill scanning (expenses/extraction/)
#
# "fake" needs no API key and no network, so a fresh clone -- and CI --
# scans bills successfully with nothing configured. Each provider reads its
# own key from its SDK's own env var (ANTHROPIC_API_KEY, GEMINI_API_KEY,
# OPENAI_API_KEY), never a BILL_SCAN_* setting: an API key is a secret, not
# a piece of app configuration, and this keeps it out of this file entirely.
BILL_SCAN_PROVIDER = env("BILL_SCAN_PROVIDER", default="fake")
BILL_SCAN_MODELS = {
    "claude": env("BILL_SCAN_CLAUDE_MODEL", default="claude-sonnet-5"),
    "gemini": env("BILL_SCAN_GEMINI_MODEL", default="gemini-2.5-flash-lite"),
    "openai": env("BILL_SCAN_OPENAI_MODEL", default="gpt-5-mini"),
}


# Media files (generated exports, uploaded bills)
MEDIA_URL = "media/"
# Overridable because the Docker image keeps media on a volume at
# /data/media, outside the code: web writes an upload that the worker
# reads, and the worker writes an export that web serves, so both mount
# the same volume. Inside /app it would also land in a bind-mounted
# checkout during development. DECISIONS D34.
MEDIA_ROOT = Path(env("MEDIA_ROOT", default=str(BASE_DIR / "media")))


# Security
# https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
#
# Gated on DEBUG because every one of these breaks local development:
# SSL redirect makes http://localhost unreachable, and secure cookies are
# not sent over plain HTTP so you cannot stay logged in.
if not DEBUG:
    # Send Strict-Transport-Security. Start LOW (a few hours) when first
    # deploying: browsers cache this, so a wrong value with preload set
    # makes the domain unreachable over HTTP for up to a year with no way
    # to take it back.
    SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=3600)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True)
    # Deliberately opt-in. Preload submits the domain to a browser-baked
    # list that is slow and painful to leave.
    SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=False)

    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=True)

    # Cookies never travel over plain HTTP. Without these, one request on a
    # hostile network hands over the session.
    #
    # Overridable for the same reason as SECURE_SSL_REDIRECT above: the local
    # compose stack serves plain HTTP, and a browser drops a Secure cookie on
    # a LAN address, so a phone on the same network could never stay logged
    # in. Only compose.yaml turns them off; a test asserts that doing so
    # fails check --deploy. DECISIONS D35.
    SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=True)
    CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=True)

    # Blocks the cookie from JavaScript, limiting what an XSS can steal.
    SESSION_COOKIE_HTTPONLY = True
    # CSRF_COOKIE_HTTPONLY stays False on purpose: it would break any
    # future JS that has to read the token for an AJAX POST.

    # Lax lets the cookie ride top-level navigations (so following a link
    # from email keeps you logged in) while blocking cross-site POSTs.
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"

    SECURE_CONTENT_TYPE_NOSNIFF = True

    # W021 warns that HSTS preload is off. That is deliberate, not an
    # oversight: preloading submits the domain to a list baked into browser
    # binaries, which takes months to undo and breaks any subdomain that
    # cannot serve HTTPS. It is a decision for a specific deployment, so the
    # check is silenced with a reason rather than satisfied by flipping a
    # flag nobody understood.
    SILENCED_SYSTEM_CHECKS = ["security.W021"]
    SECURE_REFERRER_POLICY = "same-origin"

    # Behind a reverse proxy, Django sees plain HTTP. Set only when the
    # proxy is trusted to strip a client-supplied version of this header,
    # or anyone can forge "I am on HTTPS".
    if env.bool("USE_X_FORWARDED_PROTO", default=False):
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Logging
# The default config only reports to the console when DEBUG is on, so a
# production exception is silent apart from an email to ADMINS.
LOGGING = {
    "version": 1,
    # Never True: it would kill Django's own error mail and security logging.
    "disable_existing_loggers": False,
    "filters": {
        "request_id": {"()": "config.middleware.RequestIDFilter"},
    },
    "formatters": {
        "verbose": {
            # The id sits early in the line so `grep <id> app.log` reads as
            # a transcript of one request rather than a keyword search.
            "format": "{levelname} {asctime} [{request_id}] {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
            "filters": ["request_id"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": env("LOG_LEVEL", default="INFO"),
    },
    "loggers": {
        # Requests that 4xx/5xx. Off by default without an explicit handler.
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        # Suspicious operations, host header attacks, tampered sessions.
        "django.security": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "expenses": {
            "handlers": ["console"],
            "level": env("LOG_LEVEL", default="INFO"),
            "propagate": False,
        },
    },
}


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/
REST_FRAMEWORK = {
    # Bearer tokens first: a React app on another origin and a mobile app
    # both send `Authorization: Bearer <access>`. Session auth stays so the
    # browsable API works while logged into the site. Phase 10 deferred
    # tokens until expiry had been thought about; SIMPLE_JWT below is that
    # thought. DECISIONS D41.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    # Deny by default. The alternative leaves a forgotten permission_classes
    # on one view open to the world, and nothing about the code looks wrong.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # Cursor, not page number. Offset pagination re-reads the same rows when
    # something is inserted while a client is paging, so a row can be seen
    # twice or skipped entirely. Cursor pagination is stable across writes.
    # The price is no page count and no jumping to page 7.
    "DEFAULT_PAGINATION_CLASS": "expenses.api.pagination.IdCursorPagination",
    "PAGE_SIZE": 25,
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
    ],
    # Generous enough not to annoy a real client, low enough to make a
    # runaway script or a scraper visible. A single-page app fires several
    # requests per screen and polls a scan's status, so the per-user rate
    # was raised from 1000 in phase 20 and both are now settings (D46). The
    # API login has its own, stricter limiter -- accounts/ratelimit.py.
    "DEFAULT_THROTTLE_RATES": {
        "user": env("API_USER_THROTTLE", default="3000/hour"),
        "anon": env("API_ANON_THROTTLE", default="60/hour"),
    },
    # Unset, DRF identifies an anonymous caller by the whole X-Forwarded-For
    # header -- which the caller writes -- so a new value per request resets
    # the throttle. Pinned to the same trusted-proxy count as the login limiter.
    "NUM_PROXIES": TRUSTED_PROXY_COUNT,
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.NamespaceVersioning",
    "DEFAULT_VERSION": "v1",
    "ALLOWED_VERSIONS": ["v1"],
    # The OpenAPI schema is generated from the serializers, so the contract
    # a frontend developer reads is the code (D43).
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # A delete the database protects is a 409 with a reason, not a 500.
    "EXCEPTION_HANDLER": "expenses.api.exceptions.exception_handler",
}


# Bearer tokens (DECISIONS D41)
#
# Short-lived access tokens, so a leaked one expires quickly. The refresh
# token rotates on every use and the old one is blacklisted, so a stolen
# refresh token stops working the moment the real client refreshes -- and
# logout and a password change can revoke access for real, which plain
# stateless JWT cannot.
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=env.int("JWT_ACCESS_MINUTES", default=30)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=env.int("JWT_REFRESH_DAYS", default=14)),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # Every token carries a hash of the password hash, so changing the
    # password -- through the API or a Django page -- ends every access token
    # already issued. The API's password endpoints also blacklist the
    # refresh tokens, which this check does not reach.
    "CHECK_REVOKE_TOKEN": True,
}


# Cross-origin access (DECISIONS D42)
#
# An explicit list, never a wildcard: with a wildcard any website could
# drive the API with a token it had stolen. Only /api/ is opened. Cookies
# are not allowed cross-origin -- tokens travel in the Authorization
# header -- which is also why a cross-origin request needs no CSRF token.
# Example: CORS_ALLOWED_ORIGINS=http://localhost:5173 for a Vite dev server.
CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
CORS_URLS_REGEX = r"^/api/.*$"
CORS_ALLOW_CREDENTIALS = False
# So the frontend can read the file name of a downloaded export.
CORS_EXPOSE_HEADERS = ["Content-Disposition"]

# Where the separate frontend lives, for links in emails the API sends:
# verification, password reset, export ready. Unset, those emails link to
# the Django pages, as before. DECISIONS D45.
FRONTEND_URL = env("FRONTEND_URL", default="").rstrip("/")


# The OpenAPI schema and Swagger UI at /api/v1/schema/ and /api/v1/docs/.
SPECTACULAR_SETTINGS = {
    "TITLE": "Expense Tracker API",
    "DESCRIPTION": (
        "Personal expenses, bills split between people, balances and settling up, "
        "CSV exports and bill scanning. Authenticate with `POST /api/v1/auth/login/` "
        "and send `Authorization: Bearer <access>`."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # Separate request and response components, so a generated client knows
    # that `id` is never sent and `category_name` is never accepted.
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api/v1",
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
}


# Cache
# LocMemCache by default so a fresh clone runs with no Redis. It is
# per-process, so it is also *wrong* under gunicorn with three workers --
# each would hold its own copy and a version bump in one would not reach the
# others. That is fine for development and a real bug in production, which
# is why compose sets CACHE_URL.
CACHES = {
    "default": env.cache_url(
        "CACHE_URL",
        default="locmemcache://expense-tracker",
    )
}


# Celery beat
# The digest is cron's job, not beat's -- see BUILD_LOG section 5 for that
# argument. Retention is here because it is genuinely periodic, has no
# external dependency, and running it twice is harmless: a file already
# gone stays gone.
CELERY_BEAT_SCHEDULE = {
    "purge-old-exports": {
        "task": "expenses.tasks.purge_exports",
        # Daily. Hourly would be wasted work on a table that changes slowly.
        "schedule": 24 * 60 * 60,
    },
}
