"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment. Declaring types and defaults here means a missing or
# malformed value fails loudly at startup rather than silently becoming
# a string like "False" (which is truthy).
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
)

# Read .env if present. It is gitignored; .env.example documents the keys.
environ.Env.read_env(BASE_DIR / ".env")

# SECURITY WARNING: keep the secret key used in production secret!
# No default on purpose: an unset SECRET_KEY should crash, not fall back
# to a shared value that silently ships to production.
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False so that forgetting to set it fails safe.
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "expenses",
]

# Custom user model. Must be set before the first migration is applied;
# swapping it afterwards is a painful data migration.
AUTH_USER_MODEL = "accounts.User"

# Where LoginRequiredMixin sends anonymous users, and where login/logout
# land afterwards. Accepts a URL name, so the path can change without
# touching settings.
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "expenses:dashboard"
LOGOUT_REDIRECT_URL = "expenses:dashboard"

# Email. The console backend prints messages to stdout instead of sending
# them, which is what makes the password reset flow testable in development
# without an SMTP server. Production overrides EMAIL_BACKEND via the
# environment; nothing in the code needs to change.
EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend",
)
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="no-reply@expense-tracker.local")

# How long a password reset link stays valid. Django's default is 3 days,
# which is generous for a credential-bearing URL that may sit in an inbox.
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24  # 24 hours

# Swaps in a fast password hasher for the test run only. See the module
# docstring: 20.5s -> 0.5s on the current suite.
TEST_RUNNER = "config.test_runner.FastTestRunner"


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Project-wide templates (base.html, later registration/). App
        # templates still resolve via APP_DIRS; this directory is searched
        # first, which is also how you override a third-party app's template.
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Parsed from a DATABASE_URL, so moving to Postgres later is a config
# change rather than a code change.
DATABASES = {
    "default": env.db_url(
        "DATABASE_URL",
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Celery
# https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html

# Separate Redis databases: a flushed result backend must not take the
# pending task queue with it.
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://localhost:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://localhost:6379/1")

# JSON only. Celery's old pickle serializer executes arbitrary code on
# deserialisation, so anyone who can write to the broker gets remote code
# execution on every worker.
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

CELERY_TIMEZONE = TIME_ZONE

# Acknowledge a task only after it finishes, not when it is received. If a
# worker is killed mid-task the broker redelivers it instead of losing it.
# The cost is that tasks must be idempotent, because redelivery means a task
# can run twice.
CELERY_TASK_ACKS_LATE = True

# With acks_late, a worker that has prefetched ten tasks and dies redelivers
# all ten. Fetching one at a time keeps that blast radius small; it matters
# for slow I/O-bound tasks and costs throughput only for very fast ones.
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# A hung task holds a worker process forever without these. The soft limit
# raises an exception the task can catch and clean up after; the hard limit
# kills the process.
CELERY_TASK_SOFT_TIME_LIMIT = 60 * 5
CELERY_TASK_TIME_LIMIT = 60 * 10

# Run tasks inline instead of dispatching them. Set by the test settings so
# the suite needs no broker; never enable it in production, where it would
# silently make every "background" job block the request.
CELERY_TASK_ALWAYS_EAGER = env.bool("CELERY_TASK_ALWAYS_EAGER", default=False)
CELERY_TASK_EAGER_PROPAGATES = True


# Media files (generated exports)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"
